### ISSUE TITLE
Migration from MCB

### ISSUE THREAD

**Issue by wildsurfer** [trendwerk/multiple-content-blocks#74]
My blog was successfully using this plugin for years. I really like it! Thank you! But layout of my templates has been changed and I don't need this plugin any more. I need a way to disable this plugin but keep my content. 

In other words I need a way to "glue" all existing content (thousands of posts) into main content block.

Any ideas? Possible pitfalls?

**Comment by haroldangenent** [comment]
Hi Wildsurfer,

These options seem valid:

- Display the MCB content below the normal content in your template. All MCB content is saved in WordPress' post meta table, so you could grab it from there (no need to keep using this plugin)
- Write a database migration script

Second option is obviously harder and far more time consuming, especially for a lot of posts. Hope you figure out the best option for you.

I'll close this issue for now, since it's a more general question.

**Comment by wildsurfer** [comment]
thanks! first option seems to be optimal solution
